### ISSUE TITLE
[BUG]: Dynamic link lib missed libtiff.so.5 when installing libcuspatial.so via Conda

### ISSUE THREAD

**Issue by NvTimLiu** [rapidsai/cuspatial#881]
### Version

23.02, 23.04

### On which installation method(s) does this occur?

Conda

### Describe the issue

1, Can not install cuspatial via the command line in README page [conda install -c conda-forge -c rapidsai-nightly cuspatial](https://github.com/rapidsai/cuspatial#install-from-conda), reported error as below, unless   adding channel `-c nvidia` 
  ```
  docker run -it centos:7 (below installing commands runs into the centos:7 docker container)
  
  yum update && yum install -y wget
  
  export PATH="/root/miniconda3/bin:${PATH}"
  
  wget --quiet \
      https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh \
      && mkdir /root/.conda \
      && bash Miniconda3-py38_4.10.3-Linux-x86_64.sh -b \
      && rm -f Miniconda3-py38_4.10.3-Linux-x86_64.sh \
      && conda init
  
  conda install -c conda-forge -c rapidsai-nightly cuspatial
  
  ```

Reported error as below:  `conda install -c conda-forge -c rapidsai-nightly cuspatial`

  ```
  Collecting package metadata (current_repodata.json): done
  Solving environment: failed with initial frozen solve. Retrying with flexible solve.
  Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
  Collecting package metadata (repodata.json): done
  Solving environment: failed with initial frozen solve. Retrying with flexible solve.
  Solving environment: -
  Found conflicts! Looking for incompatible packages.                                                                  failed
  
  UnsatisfiableError: The following specifications were found to be incompatible with each other:
  
  Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
  
    - feature:/linux-64::__glibc==2.17=0
    - feature:|@/linux-64::__glibc==2.17=0
    - cuspatial -> __glibc[version='>=2.17,<3.0.a0']
  
  **Your installed version is: 2.17**
  
  ```
2, Conda install cuspatial by adding channel ` -c nvidia` , the `libtiff.so.6` (4.5.0) is installed instead of `libtiff.so.5` (4.4.0), 

```
conda install -c conda-forge -c rapidsai-nightly -c nvidia cuspatial
        libtiff-4.5.0              |       h6adf6a1_2         397 KB  conda-forge
        libutf8proc-2.8.0          |       h166bdaf_0          99 KB  conda-forge
```

3, dynamic link table shows it depends on both `libtiff.so.6`  and `libtiff.so.5`, but missed `libtiff.so.5`
  ```
  ldd /root/miniconda3/lib/libcuspatial.so

           libtiff.so.6 => /root/miniconda3/lib/././libtiff.so.6 (0x00007f2e03465000)
          .....
          liblcms2.so.2 => /root/miniconda3/lib/./././liblcms2.so.2 (0x00007f2dfe850000)
          libtiff.so.5 => not found
          libnss3.so => /root/miniconda3/lib/./././libnss3.
         ....
  ```
when loading `libcuspatial.so`, it reported/failed with error missing `libtiff.so.5`, e.g., 

```
  18:36:21  Caused by: java.lang.UnsatisfiedLinkError: /tmp/spatialudfjni7296145012610170381.so: libtiff.so.5: cannot open shared object file: No such file or directory
  18:36:21  	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
  18:36:21  	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
  18:36:21  	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
  18:36:21  	at java.lang.Runtime.load0(Runtime.java:811)
  18:36:21  	at java.lang.System.load(System.java:1088)
  18:36:21  	at com.nvidia.spark.rapids.udf.UDFNativeLoader.ensureLoaded(UDFNativeLoader.java:39)
  18:36:21  	at com.nvidia.spark.rapids.udf.PointInPolygon.evaluateColumnar(PointInPolygon.java:128)
  18:36:21  	at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$4(GpuUserDefinedFunction.scala:59)
```

### Minimum reproducible example

```shell
Steps/commands to repro


docker run -it centos:7

yum update && yuminstall -y wget

export PATH="/root/miniconda3/bin:${PATH}"

wget --quiet \
    https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-py38_4.10.3-Linux-x86_64.sh -b \
    && rm -f Miniconda3-py38_4.10.3-Linux-x86_64.sh \
    && conda init

conda install -c conda-forge -c rapidsai-nightly cuspatial

conda install -c conda-forge -c rapidsai-nightly -c nvidia cuspatial

ldd /root/miniconda3/lib/libcuspatial.so | grep libtiff
```
```


### Relevant log output

```shell
When loading `libcuspatial.so`, it reported/failed with error missing `libtiff.so.5`, e.g., 


18:36:21  Caused by: java.lang.UnsatisfiedLinkError: /tmp/spatialudfjni7296145012610170381.so: libtiff.so.5: cannot open shared object file: No such file or directory
18:36:21  	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
18:36:21  	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
18:36:21  	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
18:36:21  	at java.lang.Runtime.load0(Runtime.java:811)
18:36:21  	at java.lang.System.load(System.java:1088)
18:36:21  	at com.nvidia.spark.rapids.udf.UDFNativeLoader.ensureLoaded(UDFNativeLoader.java:39)
18:36:21  	at com.nvidia.spark.rapids.udf.PointInPolygon.evaluateColumnar(PointInPolygon.java:128)
18:36:21  	at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$4(GpuUserDefinedFunction.scala:59)
```
```


### Environment details

```shell
docker run -it centos:7
```

**Comment by harrism** [comment]
I'm guessing the dependency on libtiff comes from GDAL. Once we finish dropping the GDAL dependency this shouldn't be a problem. Not sure why we have two different version dependencies.

**Comment by harrism** [comment]
@NvTimLiu can you check whether this still happens with the latest cuSpatial 23.04?

**Comment by harrism** [comment]
No response, closing.
