### ISSUE TITLE
[BUG] Unable to run trajectory clustering demo - RMM_ERROR_CUDA

### ISSUE THREAD

**Issue by NataliaVConnolly** [rapidsai/cuspatial#96]
I am trying to run the `hausdorff_clustering_test_toy.py` demo code on my G3 AWS instance.   
The code hasn't been modified in any way.   I am running in within the cudf_dev environment that I built using this command:
   
      conda env create --name cudf_dev --file conda/environments/cudf_dev_cuda10.0.yml

I installed cuspatial from source following your instructions.

The error is as follows:

Traceback (most recent call last):
  File "hausdorff_clustering_test_toy.py", line 33, in <module>
    distance = cuspatial.directed_hausdorff_distance(pnt_x, pnt_y, cnt)
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cuspatial-0.11.0a0+37.g51b2557-py3.7-linux-x86_64.egg/cuspatial/core/gis.py", line 65, in directed_hausdorff_distance
    result = cpp_directed_hausdorff_distance(x, y, count)
  File "cuspatial/_lib/spatial.pyx", line 120, in cuspatial._lib.spatial.cpp_directed_hausdorff_distance
  File "cuspatial/_lib/spatial.pyx", line 121, in cuspatial._lib.spatial.cpp_directed_hausdorff_distance
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf-0.11.0a0+1810.g4f60dae.dirty-py3.7-linux-x86_64.egg/cudf/core/series.py", line 1448, in astype
    raise e
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf-0.11.0a0+1810.g4f60dae.dirty-py3.7-linux-x86_64.egg/cudf/core/series.py", line 1444, in astype
    data=self._column.astype(dtype, **kwargs)
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf-0.11.0a0+1810.g4f60dae.dirty-py3.7-linux-x86_64.egg/cudf/core/column/column.py", line 954, in astype
    return self.as_numerical_column(dtype, **kwargs)
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf-0.11.0a0+1810.g4f60dae.dirty-py3.7-linux-x86_64.egg/cudf/core/column/numerical.py", line 172, in as_numerical_column
    data=libcudf.typecast.cast(self, dtype).data, dtype=np.dtype(dtype)
  File "cudf/_lib/typecast.pyx", line 39, in cudf._lib.typecast.cast
RuntimeError: CUDA error encountered at: /home/ubuntu/GeoSpatial/cudf/cpp/src/unary/legacy/unary_ops.cuh:66: 8 cudaErrorInvalidDeviceFunction invalid device function
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/numba/utils.py", line 754, in _exitfunc
    f()
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/numba/utils.py", line 678, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/rmm/rmm.py", line 219, in finalizer
    librmm.rmm_free(handle, stream)
  File "rmm/_lib/lib.pyx", line 239, in rmm._lib.lib.rmm_free
  File "rmm/_lib/lib.pyx", line 228, in rmm._lib.lib.c_free
  File "rmm/_lib/lib.pyx", line 48, in rmm._lib.lib.check_error
rmm.rmm.RMMError: RMM_ERROR_CUDA_ERROR

**Comment by zhangjianting** [comment]
I will look into this ASAP. It seems that you were using cuSpatial/cuDF 0.11. There were some changes on rmm in this new release.  The code were interactively tested on release 0.9 and 0.10.

**Comment by zhangjianting** [comment]
After updated my cuDF and cuSpatial codebases to the most recent ones, I did not get RMM related error but got a cudf dataframe error. I am working with my colleagues to look into the issue and will get back to you soon.

**Comment by NataliaVConnolly** [comment]
@thomcom : I build `cuSpatial` from source using instructions [here](https://github.com/rapidsai/cuspatial).   First I built `cuDF`, which didn't give any build errors but running python tests with `py.test -v` failed 

```
(cudf_dev) :~/GeoSpatial/cudf/python$ py.test -v
=================================================== test session starts ====================================================
platform linux -- Python 3.7.3, pytest-5.2.2, py-1.8.0, pluggy-0.13.0 -- /home/ubuntu/anaconda3/envs/cudf_dev/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/ubuntu/GeoSpatial/cudf/python/.hypothesis/examples')
rootdir: /home/ubuntu/GeoSpatial/cudf/python
plugins: hypothesis-4.42.0
collecting 3907 items / 1 errors / 3906 selected                                                                           Fatal Python error: Aborted

Current thread 0x00007fb77ac1f700 (most recent call first):
  File "/home/ubuntu/GeoSpatial/cudf/python/cudf/cudf/core/column/column.py", line 1174 in as_column
  File "/home/ubuntu/GeoSpatial/cudf/python/cudf/cudf/core/column/column.py", line 1225 in as_column
  File "/home/ubuntu/GeoSpatial/cudf/python/cudf/cudf/core/series.py", line 123 in __init__
  File "/home/ubuntu/GeoSpatial/cudf/python/cudf/cudf/tests/test_dataframe.py", line 2844 in <module>
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 142 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
```

**Comment by thomcom** [comment]
Hey @NataliaVConnolly a lot has been changing lately in `cudf`, the most important upstream dependency of `cuspatial`. If you try again I think you might see your problem has resolved.

**Comment by NataliaVConnolly** [comment]
Sorry, just tried again  but the error is still there.  Here's what I did:

Code:

```
import numpy as np
from sklearn.cluster import DBSCAN, AgglomerativeClustering

from cudf import Series

import cuspatial

in_trajs = []
in_trajs.append(np.array([[1, 0], [2, 1], [3, 2], [5, 3], [7, 1]]))
in_trajs.append(np.array([[0, 3], [2, 5], [3, 6], [6, 5]]))
in_trajs.append(np.array([[1, 4], [3, 7], [6, 4]]))
out_trajs = np.concatenate([np.asarray(traj) for traj in in_trajs], 0)
py_x = np.array(out_trajs[:, 0])
py_y = np.array(out_trajs[:, 1])
py_cnt = []
for traj in in_trajs:
    py_cnt.append(len(traj))
pnt_x = Series(py_x)
pnt_y = Series(py_y)
cnt = Series(py_cnt)
distance = cuspatial.directed_hausdorff_distance(pnt_x, pnt_y, cnt)
```

It's failing with this error message: 

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.6/site-packages/cuspatial/core/gis.py", line 65, in directed_hausdorff_distance
    result = cpp_directed_hausdorff_distance(x, y, count)
  File "cuspatial/_lib/spatial.pyx", line 120, in cuspatial._lib.spatial.cpp_directed_hausdorff_distance
  File "cuspatial/_lib/spatial.pyx", line 121, in cuspatial._lib.spatial.cpp_directed_hausdorff_distance
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.6/site-packages/cudf/core/series.py", line 1446, in astype
    raise e
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.6/site-packages/cudf/core/series.py", line 1442, in astype
    data=self._column.astype(dtype, **kwargs)
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.6/site-packages/cudf/core/column/column.py", line 957, in astype
    return self.as_numerical_column(dtype, **kwargs)
  File "/home/ubuntu/anaconda3/envs/cudf_dev/lib/python3.6/site-packages/cudf/core/column/numerical.py", line 173, in as_numerical_column
    data=libcudf.typecast.cast(self, dtype).data, dtype=np.dtype(dtype)
  File "cudf/_lib/typecast.pyx", line 39, in cudf._lib.typecast.cast
RuntimeError: CUDA error encountered at: /conda/conda-bld/libcudf_1575968440756/work/cpp/src/unary/legacy/unary_ops.cuh:66: 8 cudaErrorInvalidDeviceFunction invalid device function

```

  My specs:

AWS g3s.xlarge EC2

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

   What I did:

1. Build the cudf dependency from source using instructions on https://github.com/rapidsai/cudf.    The build seems to have worked, with 99% of the tests passing.   Activated the `cudf_dev` environment.

2. Installed the `rmm` dependency using `conda install -c nvidia -c rapidsai-nightly -c conda-forge -c defaults rmm=0.12 python=3.6 cudatoolkit=10.0`, as recommended on https://github.com/rapidsai/rmm.  BTW, why python 3.6 here and not 3.7, as in cudf_dev ?    This also had the side effect of changing the versions of a bunch of packages.

3. Installed `cuspatial` using `conda install -c conda-forge -c rapidsai-nightly cuspatial`.

**Comment by thomcom** [comment]
Thanks for looking again! @kkraus14, do you know if we can support this AWS instance type? g3s.xlarge presumably has the M60 GPU.

**Comment by taureandyernv** [comment]
Hey @NataliaVConnolly in the spirit of helpfully documenting for others who face similar issues, please know that you are not running a GPU enabled system. Please use a g4dn, p3, or p4 instance to run RAPIDS it should would. I regret the delay in getting back to you with a solution.

@thomcom , please close this issue. Thanks man!
